### ISSUE TITLE
unit test 작성

### ISSUE THREAD

**Issue by dayoungles** [aws-kr-tnc/moving-to-serverless-renew#19]

**Comment by dayoungles** [comment]
https://github.com/aws-kr-tnc/moving-to-serverless-renew/commit/328e339882c61e598959c69444b57bcd8bac64ae

users 관련 unit test 완료 됨

**Comment by dayoungles** [comment]
photos test::  on new_test_photos branch

**Comment by liks79** [comment]
LAB01 - LAB03/01,02,03,04 완료
