### ISSUE TITLE
/photos/{photo_id} api에서 @jwt_required 관련..

### ISSUE THREAD

**Issue by liks79** [aws-kr-tnc/moving-to-serverless-renew#25]
front-end에서 등록된 이미지를 보여줄 때에 항상 img src 항목으로 image/jpeg 헤더를 가지고 axios 를 통해서 각각의 사진마다 요청을 보내야 하는데 이 부분 구현이 복잡하여 backend에서 임시로 @jwt_required를 해제하려 놓고 먼저 front-end를 구현 하려고 합니다.

**Comment by LoveMeWithoutAll** [comment]
jwt와 함께 image를 get하는데 성공했습니다.
image blob을 v-img의 src 프로퍼티에 집어넣어 로딩되도록 해주세요.

**Comment by LoveMeWithoutAll** [comment]
blob 이미지 display 성공
하지만 vue ref의 프로퍼티를 직접 조작했기 때문에 warning 발생
추후 조치 필요함

**Comment by LoveMeWithoutAll** [comment]
> blob 이미지 display 성공
> 하지만 vue ref의 프로퍼티를 직접 조작했기 때문에 warning 발생
> 추후 조치 필요함

해결 완료

**Comment by LoveMeWithoutAll** [comment]
> jwt와 함께 image를 get하는데 성공했습니다.
> image blob을 v-img의 src 프로퍼티에 집어넣어 로딩되도록 해주세요.

해결 완료

**Comment by liks79** [comment]
감사합니다. 수고 많았습니다.
