### ISSUE TITLE
사진 업로드 오류 수정 

### ISSUE THREAD

**Issue by liks79** [aws-kr-tnc/moving-to-serverless-renew#35]
file_upload_parser 에 city, address, nation에 대한 정의가 누락되어 오류가 발생하고 있습니다.

**Comment by liks79** [comment]
수정을 완료 하였습니다.

**Comment by dayoungles** [comment]
요거 지도 안 넣기로 했을 때 제가 뺐나보네요..lab 03에는 다 살아있습니다.
