### ISSUE TITLE
S3 presigned url 사용처 

### ISSUE THREAD

**Issue by dayoungles** [aws-kr-tnc/moving-to-serverless-renew#43]
lab 03-02 S3단계에서 presigned url이 지금으로서는 적당히 꽂아넣을만한 곳이 없네요. 혹시 아이디어 있으시면 주시고, 따로 없으시면 제거하는게 좋을 것 같습니다. 

예전에는 아래 두군데에서 사용했습니다. 
GET: /photos/<photo_id>
GET/photos/search

지금 GET: /photos/<photo_id> 을 요청하면 사진 정보가 아니라 사진 컨텐츠만 내려주고 있어서 presigned url을 함께 포함해서 내려주기가 어렵네요. 일단 소스는 복사해서 넣어두긴했습니다...

**Comment by liks79** [comment]
presinged url로 기존의 /photos/{id} 요거 대체 한다고 보시면 됩니다.
기존에는 image를 리턴하는데.. s3 presigned url 이 적용되면 presigned url을 받아서 보여주는 방식으로 front-end를 변경할거예요 ^^

기존 image/jpeg으로 리턴하는 api는 주석처리 하면 될것 같습니다.

**Comment by dayoungles** [comment]
앗...그러네요. 제가 원래 소스를 잘못 봤네요;;
S3부터 그러면 photos/id에 대해서 presigned url을 내려보내는 것으로 변경하겠습니다!
