### ISSUE TITLE
lab03-03 코그니토 signup 후 어떻게 컨펌할지?

### ISSUE THREAD

**Issue by dayoungles** [aws-kr-tnc/moving-to-serverless-renew#57]
성식님, 지금은 사인업하고 나면 제가 코그니토 콘솔로 들어가서 수동으로 컨펌해주고 다음 작업으로 넘어가고 있는데요.
요거 그냥 임의로 사인업 성공하면 코드 상에서 바로 컨펌하도록 세팅을 하는게 좋을까요?
아니면 랩가이드에서  접근해서 가입된 유저를 컨펌해주는 단계를 안내하는 것도 이해에 도움이 될 것 같기도 합니다.

**Comment by liks79** [comment]
넵 confirm 자동으로 되는것이 좋을것 같습니다.

**Comment by dayoungles** [comment]
DONE
