### ISSUE TITLE
헬스 체크 로직 

### ISSUE THREAD

**Issue by dayoungles** [aws-kr-tnc/moving-to-serverless-renew#61]
prefix: site
/site/health

```
DB check
disk check
thirdparty works
other dependencies work 
```

**Comment by dayoungles** [comment]
db, disk 정도 하고.. 나머지는 그냥 주석으로

**Comment by dayoungles** [comment]
@liks79 

prefix를 admin 으로 하고 users 에서 유저 전체 리스트 보는 기능도 옮기면 좋을 것 같은데 어떻게 생각하세요?
user 정보 전체를 내려주는 기능이 users에 있어서 계속 좀 불편하긴 했거든요 ㅎㅎㅎ
```
/admin/userlist
/admin/health_check
```

**Comment by liks79** [comment]
@dayoungles , db check 정도만 하고 나머지는 주석으로 표시만 해놓으면 될거 같아요.. userlist 요런건 뭐 손아되도 될거 같습니다.

**Comment by liks79** [comment]
health_check json 응답에 hostname 이 포함되면 LAB02 에서 멀티노드로 운영하는 것 확인하는데 도움이 될것 같습니다.

참고: 

import socket

def get_ip_addr(value):
    hostname = '({0})'.format(socket.gethostname())
    return hostname
