### ISSUE TITLE
signup / signin 호출시 ValidationError 처리

### ISSUE THREAD

**Issue by liks79** [aws-kr-tnc/moving-to-serverless-renew#67]
Error 발생시 해당 message 가 필요합니다.

signup/signin 시에는 photos는 제거해야 할거 같습니다.
"ok"와 같은 Level에 Message 라는 key로 오류 내용을 보내면, front-end 에서 값을 보여 줄 수 있습니다.

"Message": "BadRequestError: Parameter validation failed: Invalid length for parameter Password, value: 2, valid range: 6-inf"

== 현재 Sample ==
{
  "ok": false,
  "photos": {
    "user": {
      "email": "aaaaa@gmail.com",
      "password": "aaa!",
      "username": "asas"
    }
  }
}

**Comment by dayoungles** [comment]
LAB01 에 대해서 그렇게 동작하던 것들 전부 Message로 변경하도록 했습니다.

**Comment by liks79** [comment]
고생 하셨습니다. ^^
chalice 정리하다 보니까.. frontend 개선사항이랑 backend 개선 사항들이 보여서 lab04 정리 하면서 그런 부분들은 직접 반영해 놓도록 하겠습니다.

**Comment by dayoungles** [comment]
카톡을 보내긴 했는데...일단 03랩도 
Signin 할 때 최상위에서 access/refresh 토큰 내려주는 것
photos get할 때 사진 직접 내려주는것
제외하면 전부 Message 키로 감싸서 내리도록 했습니다.
