### ISSUE TITLE
signout -> 로그인 화면으로 리다이렉션 안됨

### ISSUE THREAD

**Issue by dayoungles** [aws-kr-tnc/moving-to-serverless-renew#73]
03-03 cognito에서 처음 발견한 증상인데, signout하면 로그인 화면으로 갔던 것 같은데 안가네요.

찰리스 랩에서 응답은 {'ok':true}, 200으로 리스폰스 내려줘서 거기에 맞춰봐도 프론트엔드에서 리다이렉션이 안되는 것 같습니다. 
다른 랩도 그런지 확인해볼게요

**Comment by dayoungles** [comment]
3-4 xray 같은 증상 : 리다이렉션 안됨

3-1 DDB: signout버튼 누르면 signout success message 창이 두번 뜨고 login 화면으로 리다이렉션 됨
S3도 두번 두번뜨고 로그인 화면으로 리다이렉션 됨

코그니토 문젠가보네요...?

**Comment by liks79** [comment]
테스트 해보고 수정해 보겠습니다.

**Comment by liks79** [comment]
@LoveMeWithoutAll , 영선님 fix 해주셔서 감사합니다.
